name: PR validation

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install Yarn # required for integration tests
        run: npm install -g yarn

      - name: Setup Git Credentials
        run: |
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/1inch/".insteadOf "git@github.com/1inch/"
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/1inch/".insteadOf "ssh://git@github.com/1inch/"
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/1inch/".insteadOf "git+ssh://git@github.com/1inch/"
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/1inch/".insteadOf "https://github.com/1inch/"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}

      - name: Auth in GitHub private registry npm
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@1inch:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Install Dependencies
        run: pnpm install

      - name: Linter
        run: pnpm lint

      - name: Types
        run: pnpm lint:types

      - name: Unit tests
        run: pnpm test

      - name: Integration tests
        run: pnpm test:integration
